/**
 * The stylesheet is pulled in for its side effect — NativeWind's Metro
 * transformer turns it into the style registry — so there is nothing to import
 * and TypeScript needs telling the module exists.
 */
declare module "*.css";

/**
 * Image imports resolve to an asset id at build time, which is what `Image`'s
 * `source` takes.
 *
 * Expo generates an `expo-env.d.ts` carrying these, but it is generated by
 * `expo start` and gitignored — so a clean checkout typechecks against nothing
 * until somebody has run the dev server. Declaring them here means `tsc` says
 * the same thing on a fresh clone as it does on this machine.
 */
declare module "*.png" {
    const asset: number;
    export default asset;
}
declare module "*.jpg" {
    const asset: number;
    export default asset;
}
declare module "*.svg" {
    const asset: number;
    export default asset;
}
