import {
    clearTokens,
    getAccessToken,
    getRefreshToken,
    setTokens,
} from "../session/tokens";
import { NetworkError } from "./api.types";
import type {
    ApiErrorResponse,
    ApiResponse,
    CursorMeta,
    SessionResponse,
} from "./api.types";

const REQUEST_TIMEOUT_MS = 15_000;

/**
 * The header the API reads. Lower-cased by Fastify either way.
 *
 * Kept here rather than beside `newIdempotencyKey`, which imports
 * `expo-crypto`: the transport only needs the header's name, and pulling a
 * native module into its import graph for a string would put one in the way of
 * every test that touches the client.
 */
export const IDEMPOTENCY_HEADER = "Idempotency-Key";

/**
 * `EXPO_PUBLIC_` variables are inlined into the bundle at build time, which is
 * why this is a URL and not a secret. The fallback is the local backend the
 * other repos expect during development.
 */
export const BASE_URL =
    process.env.EXPO_PUBLIC_API_URL ?? "http://localhost:8080/api/v1";

type SessionExpiredHandler = () => void;
let _onSessionExpired: SessionExpiredHandler | null = null;

export const registerSessionExpiredHandler = (
    handler: SessionExpiredHandler,
): void => {
    _onSessionExpired = handler;
};

interface ApiOptions extends RequestInit {
    /**
     * Readable with or without a session. A 401 means the token is stale, so
     * the request is replayed anonymously and a refresh runs in the
     * background — the content still arrives, just unauthenticated.
     */
    isPublic?: boolean;
    /**
     * Called to obtain a session rather than with one: login, register,
     * password reset, account recovery, OAuth exchange. No token is sent, and
     * a 401 is the endpoint's own answer — "those credentials are wrong" —
     * not a stale session. It is handed to the caller untouched, with no
     * replay and no refresh.
     */
    isAnonymous?: boolean;
    _retry?: boolean;
    contentType?: boolean;
    /**
     * Makes a retry of this request safe.
     *
     * Generated by the caller, once per user action, and reused for every
     * attempt at it — see `idempotency.ts`. Accepted by eight write endpoints
     * and ignored everywhere else.
     */
    idempotencyKey?: string;
    /**
     * Return the whole `{ data, meta }` document instead of unwrapping `data`.
     *
     * Internal — reach it through `api.getPage`, which types the envelope. It
     * exists because cursor-paginated listings keep their cursor in `meta`,
     * and unwrapping throws that away.
     */
    _envelope?: boolean;
}

let isRefreshing = false;

/**
 * Reads a response body as JSON, turning anything unreadable into a problem
 * document instead of letting it escape as a bare `SyntaxError`.
 *
 * An empty body, an HTML error page from a proxy, or a plugin that answered
 * outside the API's error format all otherwise throw a `SyntaxError`, which
 * carries neither `status` nor `title` — so the caller can say nothing better
 * than "an unexpected error occurred" and the real status code never reaches
 * it. That is the least useful message the app can show and the hardest to
 * chase.
 */
const readBody = async (
    response: Response,
): Promise<
    { ok: true; body: unknown } | { ok: false; body: ApiErrorResponse }
> => {
    const text = await response.text();

    if (text) {
        try {
            return { ok: true, body: JSON.parse(text) };
        } catch {
            // fall through to the problem document below
        }
    }

    return {
        ok: false,
        body: {
            // Marks the document as ours rather than the server's, so the
            // error layer knows the wording is safe to translate.
            type: "tdn:unreadable-response",
            title: response.statusText || "Unreadable response",
            status: response.status,
            detail: text
                ? `The server answered ${response.status} with a body that is not JSON.`
                : `The server answered ${response.status} with an empty body.`,
            instance: "",
        },
    };
};

/**
 * The in-flight refresh, shared by every caller that needs one.
 *
 * The queue below serialises *authenticated* retries, but the public branch
 * would otherwise escape it entirely. Opening an article fires several public
 * reads at once — the article, its comments, the trending rail — and with a
 * stale token each one would ask for its own refresh. That spends a
 * five-a-minute budget three at a time, and because the refresh token rotates,
 * the later calls present one the first has already consumed.
 */
let refreshPromise: Promise<string | null> | null = null;
let failedQueue: Array<{
    resolve: (token: string | null) => void;
    reject: (error: unknown) => void;
}> = [];

const processQueue = (error: unknown, token: string | null = null) => {
    failedQueue.forEach((prom) => {
        if (error) prom.reject(error);
        else prom.resolve(token);
    });
    failedQueue = [];
};

/**
 * Every request leaves through here so the 15 s budget and the `NetworkError`
 * wrapping apply to all of them. Calling `fetch` directly skips both: the
 * request can hang indefinitely, and a connection failure surfaces as a raw
 * `TypeError`, which the error layer reports as "an unexpected error" instead
 * of a connection problem.
 *
 * There is no `credentials: "include"` here, unlike the web client. A native
 * client has no cookie jar; the refresh token travels in the body, both ways.
 */
const fetchWithTimeout = async (
    endpoint: string,
    init: RequestInit = {},
): Promise<Response> => {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

    try {
        return await fetch(`${BASE_URL}${endpoint}`, {
            ...init,
            signal: controller.signal,
        });
    } catch (err) {
        const isAbort = err instanceof Error && err.name === "AbortError";
        throw new NetworkError(
            isAbort ? "Request timed out" : "Network request failed",
        );
    } finally {
        clearTimeout(timeoutId);
    }
};

/**
 * Renews the session on the body channel, and stores **both** tokens.
 *
 * Every refresh rotates: the response carries a new refresh token as well as a
 * new access token. The web client only ever stored the access token, because
 * its refresh token lived in a cookie the server rewrote. Dropping the rotated
 * token here would work until the old one is retired, and then sign the
 * account out — with the previous token now looking to the server exactly like
 * a replay.
 *
 * Exactly one attempt, deliberately. Inside the server's 30 s rotation grace
 * window a refresh whose response was lost is already served normally, so a
 * retry buys nothing; past that window a second attempt with a retired token
 * is precisely what reuse detection is watching for, and it revokes every
 * session on every device.
 */
const attemptTokenRefresh = async (): Promise<string | null> => {
    try {
        const refreshToken = await getRefreshToken();
        // Nothing to renew. Asking anyway answers 401 and spends a request
        // against a 5-per-minute budget.
        if (!refreshToken) return null;

        // A hang here would strand every queued request, so this needs the
        // timeout more than most.
        const refreshRes = await fetchWithTimeout("/auth/refresh", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ refreshToken }),
        });

        if (refreshRes.ok) {
            const refreshBody = (await refreshRes.json()) as {
                data?: SessionResponse;
            };
            const session = refreshBody.data;
            if (session?.accessToken) {
                await setTokens({
                    accessToken: session.accessToken,
                    refreshToken: session.refreshToken,
                });
                return session.accessToken;
            }
        }
    } catch {
        // network error — fall through
    }
    return null;
};

const refreshOnce = (): Promise<string | null> => {
    if (!refreshPromise) {
        refreshPromise = attemptTokenRefresh().finally(() => {
            refreshPromise = null;
        });
    }
    return refreshPromise;
};

/** Everything a failed refresh has to undo, in one place. */
const endSession = async (): Promise<void> => {
    await clearTokens();
    _onSessionExpired?.();
};

/**
 * `data` or the whole document, depending on what the caller asked for.
 *
 * The cast is the price of one client serving both shapes: when `_envelope` is
 * set the caller's `T` *is* the envelope type, which `api.getPage` fixes for
 * it, so no call site has to state the relationship itself.
 */
const unwrap = <T>(body: unknown, envelope: boolean): T =>
    (envelope ? body : (body as ApiResponse<T>).data) as T;

export const apiClient = async <T>(
    endpoint: string,
    options: ApiOptions = {},
): Promise<T> => {
    const {
        isPublic = false,
        isAnonymous = false,
        _retry = false,
        contentType = true,
        idempotencyKey,
        _envelope = false,
        ...fetchOptions
    } = options;
    const token = isAnonymous ? null : getAccessToken();

    const headers = new Headers(fetchOptions.headers);

    if (
        contentType &&
        fetchOptions.body &&
        !(fetchOptions.body instanceof FormData)
    ) {
        headers.set("Content-Type", "application/json");
    }

    if (token) {
        headers.set("Authorization", `Bearer ${token}`);
    }

    if (idempotencyKey) {
        headers.set(IDEMPOTENCY_HEADER, idempotencyKey);
    }

    const response = await fetchWithTimeout(endpoint, {
        ...fetchOptions,
        headers,
    });

    // A public request that carried no token was already anonymous, so its
    // 401 is the endpoint's own answer rather than a stale session. Retrying
    // it unchanged only repeats the same failure, and renewing a session that
    // was never opened ends by reporting it expired — which puts the sign-in
    // screen in front of a reader who never signed in.
    const isStaleSession =
        response.status === 401 &&
        !_retry &&
        !isAnonymous &&
        !(isPublic && !token);

    if (isStaleSession) {
        // Public endpoints: retry without the token so the request succeeds
        // as unauthenticated, then attempt a background refresh. Shared with
        // every other caller, so a screen full of public reads renews the
        // session once rather than once each.
        if (isPublic) {
            headers.delete("Authorization");
            const retryRes = await fetchWithTimeout(endpoint, {
                ...fetchOptions,
                headers,
            });

            void refreshOnce().then((newToken) => {
                if (!newToken) void endSession();
            });

            if (retryRes.status === 204) return {} as T;
            const retryParsed = await readBody(retryRes);
            if (!retryParsed.ok) throw retryParsed.body;
            if (!retryRes.ok) throw retryParsed.body as ApiErrorResponse;
            return unwrap<T>(retryParsed.body, _envelope);
        }

        // Authenticated endpoints: queue behind an in-flight refresh.
        if (isRefreshing) {
            return new Promise<string | null>((resolve, reject) => {
                failedQueue.push({ resolve, reject });
            }).then(() => apiClient<T>(endpoint, { ...options, _retry: true }));
        }

        isRefreshing = true;

        const newToken = await refreshOnce();
        if (newToken) {
            processQueue(null, newToken);
            isRefreshing = false;
            return apiClient<T>(endpoint, { ...options, _retry: true });
        }

        isRefreshing = false;
        processQueue(new Error("Session Expired"), null);
        await endSession();
        throw new Error("Session Expired");
    }

    // Answered before the envelope branch below, and the same either way: a
    // 204 has no document to hand back.
    if (response.status === 204) {
        return {} as T;
    }

    const parsed = await readBody(response);

    if (!parsed.ok) {
        throw parsed.body;
    }

    if (!response.ok) {
        throw parsed.body as ApiErrorResponse;
    }

    return unwrap<T>(parsed.body, _envelope);
};

export const api = {
    get: <T>(url: string, options?: ApiOptions) =>
        apiClient<T>(url, { ...options, method: "GET" }),
    post: <T>(url: string, body?: unknown, options?: ApiOptions) =>
        apiClient<T>(url, {
            ...options,
            method: "POST",
            body: body instanceof FormData ? body : JSON.stringify(body),
        }),
    delete: <T>(url: string, options?: ApiOptions) =>
        apiClient<T>(url, { ...options, method: "DELETE" }),
    patch: <T>(url: string, body?: unknown, options?: ApiOptions) =>
        apiClient<T>(url, {
            ...options,
            method: "PATCH",
            body: body instanceof FormData ? body : JSON.stringify(body),
        }),
    /**
     * A cursor-paginated GET: the rows *and* the cursor that reaches the next
     * page, which `api.get` would discard along with the rest of `meta`.
     *
     * Use it only where the endpoint is cursor-paginated. Everything paged by
     * `page`/`limit` stays on `api.get` — it has no cursor to lose.
     */
    getPage: <T>(url: string, options?: ApiOptions) =>
        apiClient<ApiResponse<T, CursorMeta>>(url, {
            ...options,
            method: "GET",
            _envelope: true,
        }),
};
